[package]
name = "msl_script_tools"
version = "0.2.0"
authors = ["Misty De Meo <mistydemeo@gmail.com>"]

[dependencies]
byteorder = "1.1.0"
clap = "2.24.2"
csv = "1.0.0-beta.3"
encoding_rs = "0.6.11"
fldtools = "0.1.1"
serde = "1.0.10"
serde_derive = "1.0.10"
